services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: big_jhon_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: >
      sh -c "
      sleep 5 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py seed_users &&
      python manage.py seed_appointments &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
