services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: big-jhon-test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  # backend:
  #   build: ./backend
  #   command: uv run python manage.py runserver
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
