# Generated by Django 6.0.3 on 2026-03-21 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('supplier', models.CharField(choices=[('SAMARA', 'Samara Ropa intima'), ('URBAN', 'Costura Urbana'), ('GOLDEN', 'Hilo Dorado')], max_length=20)),
                ('product_line', models.CharField(choices=[('SHIRTS', 'Camisetas'), ('PANTS', 'Pantalones'), ('SHOES', 'Zapatos'), ('ACCESSORIES', 'Accesorios')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('IN_PROGRESS', 'En proceso'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
