const ENDPOINTS = {
  LOGIN: 'users/login/',
  LOGOUT: 'users/logout/',
  DASHBOARD: 'appointments/dashboard/',
  SUPPLIERS: 'appointments/suppliers/',
  PRODUCT_LINES: 'appointments/product-lines/',
  APPOINTMENTS_STATUSES: 'appointments/statuses/',
  APPOINTMENTS_LIST: 'appointments/list/',
  ////
  CREATE_USER: 'auth/register',
  FIND_USER_BY_EMAIL: 'auth/find-by-email',
  DEPARTMENTS: 'departments',
  MUNICIPALITIES: 'municipalities',
  DOCUMENT_TYPES: 'document-types',
  EPS: 'eps',
  AFP: 'afp',
  OFFERS: 'offers',
  OFFERS_ID: (id: number) => `offers/${id}`,
  PROSPECTS: 'prospects',
  POSITIONS: 'positions',
  POSITIONS_ID: (id: number) => `positions/${id}`,
  LOCATIONS: 'locations',
  LOCATONS_ID: (id: number) => `locations/${id}`,
  CANDIDATES: 'candidates',
  CANDIDATES_DETAIL: (id: number) => `candidates/${id}`,
  SELECTION_PROCESS_TYPE_STEPS_BY_TYPE: (fkType: number) =>
    `selection-process-type-steps/by-type/${fkType}`,
  SELECTION_PROCESS_TYPE_STEPS: 'selection-process-type-steps',
  SELECTION_PROCESS_TYPE_STEPS_ID: (id: number) => `selection-process-type-steps/${id}`,
  SELECTION_PROCESS_STEPS: 'selection-process-steps',
  SELECTION_PROCESS_STEPS_ID: (id: number) => `selection-process-steps/${id}`,
  SELECTION_PROCESS_STEPS_NOT_APPLIED_CANDIDATE: (fkCandidate: number) =>
    `selection-process-steps/available-for-candidate/${fkCandidate}`,
  CANDIDATE_PROCESS_STEPS: 'candidate-proccess-steps',
  CANDIDATE_DOCUMENTS: 'candidate-documents',
  CANDIDATE_DOCUMENTS_UPDATE: (id: number) => `candidate-documents/${id}`,
  PROSPECT_BY_EMAIL: (email: string) => `prospects/email/${email}`,
  CANDIDATES_WITH_DOCUMENTS: 'candidate-documents/all-candidates',
  DOCUMENTS_OF_A_CANDIDATE: (id: number) => `candidate-documents/by-candidate/${id}`,
  CANDIDATE_DOCUMENTS_MUST_UPLOAD: (id: number) => `candidate-documents/missing-or-rejected/${id}`,
  HIRING_DOCUMENTS: 'hiring-documents',
  INDUCTIONS: 'inductions',
  INDUCTIONS_DETAIL: (id: number) => `inductions/${id}`,
  INDUCTIONS_BY_CANDIDATE: (id: number) => `inductions/candidate/${id}`,
  CANDIDATE_DOCUMENTS_TYPE: 'candidate-documents-type',
  CANDIDATE_DOCUMENTS_TYPE_ID: (id: number) => `candidate-documents-type/${id}`,
  HIRING_DOCUMENTS_ALL_CANDIDATES: 'hiring-documents/candidates',
  HIRING_DOCUMENTS_EXPORT_EXCEL: 'hiring-documents/candidates-export-excel',
  LOG_PROSPECT: 'log-prospects',
  SEND_EMAIL: 'email/send',
  SELECTION_PROCESS_TYPES: 'selection-process-types',
  SELECTION_PROCESS_TYPES_ID: (id: number) => `selection-process-types/${id}`,
  USERS: 'users',
  USERS_ID: (id: number) => `users/${id}`,
  USERS_FIND_PERMISSIONS: 'users/find-permissions',
  PERMISSIONS: 'permissions',
  PERMISSIONS_ID: (id: number) => `permissions/${id}`,
  ROLES: 'roles',
  ROLES_ID: (id: number) => `roles/${id}`,
  ROLE_PERMISSIONS: 'role-permissions',
  ROLE_PERMISSIONS_ID: (id: number) => `role-permissions/${id}`,
  USER_ROLES: 'user-roles',
  USER_ROLES_ID: (id: number) => `user-roles/${id}`,
  USER_LOCATIONS: 'user-locations',
  USER_LOCATIONS_ID: (id: number) => `user-locations/${id}`
}

export default ENDPOINTS
